export const productDatabase = {
  "beef-cubes": {
    name: "Beef Cubes",
    nameAr: "مكعبات لحم بقري",
    category: "Frozen Meat",
    categoryAr: "اللحوم المجمدة",
    price: "AED 45",
    img: "/products/beef-cubes.png",
    description:
      "Premium halal-certified beef cubes, hand-selected and vacuum-packed for maximum freshness. Perfect for stews, curries, and grilling.",
    descriptionAr:
      "مكعبات لحم بقري ممتازة معتمدة حلال، مختارة يدوياً ومعبأة بالتفريغ الهوائي للحفاظ على أقصى درجات الطزاجة. مثالية للطهي واليخنات والشواء.",
    specifications: {
      weight: ["500g", "1kg", "Bulk Packaging"],
      weightAr: ["٥٠٠ غرام", "١ كجم", "تعبئة بالجملة"],
      origin: "UAE",
      originAr: "الإمارات",
      storage: "-18°C",
      storageAr: "-١٨ درجة مئوية",
      packaging: ["Vacuum Sealed", "Frozen Packs"],
      packagingAr: ["مغلق ومفرغ من الهواء", "عبوات مجمدة"],
    },
    benefits: [
      "100% Halal Certified",
      "Fresh Vacuum-Packed",
      "No Additives or Preservatives",
      "Perfect for Cooking",
    ],
    benefitsAr: [
      "حلال معتمد ١٠٠٪",
      "مغلق طازج بالتفريغ الهوائي",
      "خالٍ من المواد الحافظة والمضافة",
      "مثالي للطهي السريع",
    ],
  },
  "lamb-chops": {
    name: "Lamb Chops",
    nameAr: "ريش لحم ضأن",
    category: "Frozen Meat",
    categoryAr: "اللحوم المجمدة",
    price: "AED 55",
    img: "/products/lamb-chops.png",
    description:
      "Tender lamb chops, carefully selected and frozen to preserve quality. Ideal for grilling and traditional meat preparations.",
    descriptionAr:
      "ريش لحم ضأن طرية، مختارة بعناية ومجمدة للحفاظ على جودتها العالية. مثالية للشواء وتحضير أطباق اللحوم التقليدية.",
    specifications: {
      weight: ["500g", "1kg", "Bulk Packaging"],
      weightAr: ["٥٠٠ غرام", "١ كجم", "تعبئة بالجملة"],
      origin: "UAE",
      originAr: "الإمارات",
      storage: "-18°C",
      storageAr: "-١٨ درجة مئوية",
      packaging: ["Vacuum Sealed", "Frozen Packs"],
      packagingAr: ["مغلق ومفرغ من الهواء", "عبوات مجمدة"],
    },
    benefits: ["Premium Quality Cuts", "100% Halal Certified", "Long Shelf Life", "Ready to Cook"],
    benefitsAr: ["قطعيات ذات جودة ممتازة", "حلال معتمد ١٠٠٪", "صلاحية تخزين طويلة", "جاهز للطهي"],
  },
  "beef-mince": {
    name: "Beef Mince",
    nameAr: "لحم بقري مفروم",
    category: "Frozen Meat",
    categoryAr: "اللحوم المجمدة",
    price: "AED 35",
    img: "/products/beef-mince.png",
    description:
      "Finely ground beef mince, perfect for burgers, meatballs, kebabs, and traditional meat dishes. Lean and high-quality.",
    descriptionAr:
      "لحم بقري مفروم ناعم ممتاز، مثالي للبرجر، كرات اللحم، الكباب، وأطباق اللحوم التقليدية. قليل الدسم وذو جودة عالية.",
    specifications: {
      weight: ["500g", "1kg", "Bulk Packaging"],
      weightAr: ["٥٠٠ غرام", "١ كجم", "تعبئة بالجملة"],
      origin: "UAE",
      originAr: "الإمارات",
      storage: "-18°C",
      storageAr: "-١٨ درجة مئوية",
      packaging: ["Vacuum Sealed", "Frozen Packs"],
      packagingAr: ["مغلق ومفرغ من الهواء", "عبوات مجمدة"],
    },
    benefits: [
      "Lean Meat Quality",
      "100% Halal Certified",
      "Versatile for All Dishes",
      "Uniform Grind",
    ],
    benefitsAr: [
      "لحم قليل الدسم ذو جودة عالية",
      "حلال معتمد ١٠٠٪",
      "متعدد الاستخدامات لجميع الأطباق",
      "فرن متناسق وموحد",
    ],
  },
  "mutton-cuts": {
    name: "Mutton Cuts",
    nameAr: "قطع لحم غنم / ماعز",
    category: "Frozen Meat",
    categoryAr: "اللحوم المجمدة",
    price: "AED 50",
    img: "/products/mutton-cuts.png",
    description:
      "Premium mutton cuts with authentic flavor. Perfect for traditional curries, stews, and slow-cooked dishes.",
    descriptionAr:
      "قطع لحم غنم ممتازة بنكهة أصلية غنية. مثالية لليخنات، الكاري التقليدي، والأطباق التي تتطلب طهياً بطيئاً.",
    specifications: {
      weight: ["500g", "1kg", "Bulk Packaging"],
      weightAr: ["٥٠٠ غرام", "١ كجم", "تعبئة بالجملة"],
      origin: "UAE",
      originAr: "الإمارات",
      storage: "-18°C",
      storageAr: "-١٨ درجة مئوية",
      packaging: ["Vacuum Sealed", "Frozen Packs"],
      packagingAr: ["مغلق ومفرغ من الهواء", "عبوات مجمدة"],
    },
    benefits: [
      "Authentic Flavor",
      "100% Halal Certified",
      "Perfect for Traditional Dishes",
      "High Protein Content",
    ],
    benefitsAr: [
      "نكهة أصلية وتقليدية",
      "حلال معتمد ١٠٠٪",
      "مثالي للأطباق الشعبية والتقليدية",
      "محتوى عالٍ من البروتين",
    ],
  },
  "chicken-breast": {
    name: "Chicken Breast",
    nameAr: "صدور دجاج",
    category: "Frozen Chicken",
    categoryAr: "الدجاج المجمد",
    price: "AED 28",
    img: "/products/chicken-breast.png",
    description:
      "Skinless chicken breast fillets, lean and protein-rich. Perfect for health-conscious cooking and versatile recipes.",
    descriptionAr:
      "صدور دجاج فيليه بدون جلد، قليلة الدهون وغنية بالبروتين. مثالية للطهي الصحي وإعداد مختلف الوصفات اللذيذة.",
    specifications: {
      weight: ["500g", "1kg", "Bulk Packaging"],
      weightAr: ["٥٠٠ غرام", "١ كجم", "تعبئة بالجملة"],
      origin: "UAE",
      originAr: "الإمارات",
      storage: "-18°C",
      storageAr: "-١٨ درجة مئوية",
      packaging: ["Vacuum Sealed", "Frozen Packs"],
      packagingAr: ["مغلق ومفرغ من الهواء", "عبوات مجمدة"],
    },
    benefits: ["High in Protein", "100% Halal Certified", "Low Fat Content", "Quick to Cook"],
    benefitsAr: [
      "غني بالبروتين لبناء العضلات",
      "حلال معتمد ١٠٠٪",
      "محتوى دهون منخفض جداً",
      "سهل وسريع الطهي",
    ],
  },
  "chicken-wings": {
    name: "Chicken Wings",
    nameAr: "أجنحة دجاج",
    category: "Frozen Chicken",
    categoryAr: "الدجاج المجمد",
    price: "AED 24",
    img: "/products/chicken-wings.png",
    description:
      "Delicious chicken wings, perfect for grilling, frying, or baking with your favorite sauces and marinades.",
    descriptionAr:
      "أجنحة دجاج لذيذة وطازجة، مثالية للشواء أو القلي أو الخبز في الفرن مع الصلصات والتتبيلات المفضلة لديك.",
    specifications: {
      weight: ["500g", "1kg", "Bulk Packaging"],
      weightAr: ["٥٠٠ غرام", "١ كجم", "تعبئة بالجملة"],
      origin: "UAE",
      originAr: "الإمارات",
      storage: "-18°C",
      storageAr: "-١٨ درجة مئوية",
      packaging: ["Vacuum Sealed", "Frozen Packs"],
      packagingAr: ["مغلق ومفرغ من الهواء", "عبوات مجمدة"],
    },
    benefits: ["Perfect for BBQ", "100% Halal Certified", "Flavorful Meat", "Family Friendly"],
    benefitsAr: [
      "مثالي لحفلات الشواء والـ BBQ",
      "حلال معتمد ١٠٠٪",
      "لحم طري ومليء بالنكهة",
      "مفضل لجميع أفراد العائلة",
    ],
  },
  "whole-chicken": {
    name: "Whole Chicken",
    nameAr: "دجاجة كاملة",
    category: "Frozen Chicken",
    categoryAr: "الدجاج المجمد",
    price: "AED 32",
    img: "/products/whole-chicken.png",
    description:
      "Whole frozen chicken, perfectly portioned and ready for your recipes. Great for roasting, grilling, or cooking.",
    descriptionAr:
      "دجاجة كاملة مجمدة ومحفوظة بعناية، جاهزة للتحضير والطهي. رائعة للتحمير في الفرن أو الشواء أو الطهي التقليدي.",
    specifications: {
      weight: ["1kg", "1.5kg", "Bulk Packaging"],
      weightAr: ["١ كجم", "١.٥ كجم", "تعبئة بالجملة"],
      origin: "UAE",
      originAr: "الإمارات",
      storage: "-18°C",
      storageAr: "-١٨ درجة مئوية",
      packaging: ["Vacuum Sealed", "Frozen Packs"],
      packagingAr: ["مغلق ومفرغ من الهواء", "عبوات مجمدة"],
    },
    benefits: ["Complete Bird", "100% Halal Certified", "Versatile Cooking", "Great Value"],
    benefitsAr: [
      "دجاجة كاملة نظيفة وجاهزة",
      "حلال معتمد ١٠٠٪",
      "متعددة طرق التحضير والطهي",
      "قيمة ممتازة مقابل السعر",
    ],
  },
  drumsticks: {
    name: "Drumsticks",
    nameAr: "أفخاذ دجاج (دبوس)",
    category: "Frozen Chicken",
    categoryAr: "الدجاج المجمد",
    price: "AED 20",
    img: "/products/drumsticks.png",
    description:
      "Chicken drumsticks with skin, juicy and flavorful. Perfect for grilling, deep frying, or baking.",
    descriptionAr:
      "أفخاذ دجاج (دبوس) طرية وعصارية بالجلد. مثالية للشواء أو القلي العميق أو الخبز بالفرن مع التتبيلة.",
    specifications: {
      weight: ["500g", "1kg", "Bulk Packaging"],
      weightAr: ["٥٠٠ غرام", "١ كجم", "تعبئة بالجملة"],
      origin: "UAE",
      originAr: "الإمارات",
      storage: "-18°C",
      storageAr: "-١٨ درجة مئوية",
      packaging: ["Vacuum Sealed", "Frozen Packs"],
      packagingAr: ["مغلق ومفرغ من الهواء", "عبوات مجمدة"],
    },
    benefits: ["Juicy & Flavorful", "100% Halal Certified", "Kids Favorite", "Great for Grilling"],
    benefitsAr: [
      "لحم طري وعصاري ومليء بالنكهة",
      "حلال معتمد ١٠٠٪",
      "الوجبة المفضلة للأطفال",
      "رائعة للشواء والقلي",
    ],
  },
  "fish-fillets": {
    name: "Fish Fillets",
    nameAr: "فيليه سمك",
    category: "Frozen Seafood",
    categoryAr: "المأكولات البحرية المجمدة",
    price: "AED 42",
    img: "/products/fish-fillets.jpg",
    description:
      "Fresh fish fillets, deboned and ready to cook. Perfect for frying, grilling, or baking with minimal preparation.",
    descriptionAr:
      "شرائح فيليه سمك طازجة خالية تماماً من العظام وجاهزة للطهي مباشرة. مثالية للقلي أو الشواء أو الخبز بتجهيز بسيط.",
    specifications: {
      weight: ["500g", "1kg", "Bulk Packaging"],
      weightAr: ["٥٠٠ غرام", "١ كجم", "تعبئة بالجملة"],
      origin: "UAE",
      originAr: "الإمارات",
      storage: "-18°C",
      storageAr: "-١٨ درجة مئوية",
      packaging: ["Vacuum Sealed", "Frozen Packs"],
      packagingAr: ["مغلق ومفرغ من الهواء", "عبوات مجمدة"],
    },
    benefits: ["Boneless Fillets", "100% Halal Certified", "Omega-3 Rich", "Quick to Prepare"],
    benefitsAr: [
      "شرائح فيليه خالية من الشوك والعظم",
      "حلال معتمد ١٠٠٪",
      "غني بأوميغا-٣ الصحي",
      "سريع التحضير والطهي",
    ],
  },
  shrimps: {
    name: "Shrimps",
    nameAr: "روبيان (جمبري)",
    category: "Frozen Seafood",
    categoryAr: "المأكولات البحرية المجمدة",
    price: "AED 68",
    img: "/products/shrimps.jpg",
    description:
      "Large, succulent shrimps perfect for grilling, frying, or adding to your favorite seafood dishes.",
    descriptionAr:
      "روبيان (جمبري) كبير الحجم وعصاري، مثالي للشواء أو القلي أو الإضافة إلى أطباق ثمار البحر والباستا المفضلة لديك.",
    specifications: {
      weight: ["500g", "1kg", "Bulk Packaging"],
      weightAr: ["٥٠٠ غرام", "١ كجم", "تعبئة بالجملة"],
      origin: "UAE",
      originAr: "الإمارات",
      storage: "-18°C",
      storageAr: "-١٨ درجة مئوية",
      packaging: ["Vacuum Sealed", "Frozen Packs"],
      packagingAr: ["مغلق ومفرغ من الهواء", "عبوات مجمدة"],
    },
    benefits: [
      "Large & Succulent",
      "100% Halal Certified",
      "Premium Quality",
      "Restaurant Quality",
    ],
    benefitsAr: [
      "حبات كبيرة الحجم وعصارية",
      "حلال معتمد ١٠٠٪",
      "جودة تصدير ممتازة",
      "جودة تضاهي المطاعم الفاخرة",
    ],
  },
  salmon: {
    name: "Salmon",
    nameAr: "سلمون",
    category: "Frozen Seafood",
    categoryAr: "المأكولات البحرية المجمدة",
    price: "AED 85",
    img: "/products/salmon.jpg",
    description:
      "Premium salmon steaks and fillets, rich in omega-3s. Perfect for a healthy and delicious meal.",
    descriptionAr:
      "شرائح سلمون فاخرة وممتازة غنية بالدهون الصحية وأوميغا-٣. الاختيار الأمثل لوجبة صحية، مغذية ولذيذة جداً.",
    specifications: {
      weight: ["500g", "1kg", "Bulk Packaging"],
      weightAr: ["٥٠٠ غرام", "١ كجم", "تعبئة بالجملة"],
      origin: "UAE",
      originAr: "الإمارات",
      storage: "-18°C",
      storageAr: "-١٨ درجة مئوية",
      packaging: ["Vacuum Sealed", "Frozen Packs"],
      packagingAr: ["مغلق ومفرغ من الهواء", "عبوات مجمدة"],
    },
    benefits: ["High Omega-3", "Premium Quality", "Heart Healthy", "Gourmet Choice"],
    benefitsAr: [
      "محتوى عالٍ جداً من أوميغا-٣",
      "قطعيات ممتازة فاخرة",
      "مفيد جداً لصحة القلب",
      "اختيار الذواقة الأول",
    ],
  },
  "squid-rings": {
    name: "Squid Rings",
    nameAr: "حلقات حبار (كالاماري)",
    category: "Frozen Seafood",
    categoryAr: "المأكولات البحرية المجمدة",
    price: "AED 48",
    img: "/products/squid-rings.jpg",
    description:
      "Tender squid rings, ready-sliced and frozen. Perfect for deep frying or grilling.",
    descriptionAr:
      "حلقات حبار (كالاماري) طرية، مقطعة وجاهزة ومجمدة. مثالية للقلي السريع المقرمش أو الشواء بالفرن.",
    specifications: {
      weight: ["500g", "1kg", "Bulk Packaging"],
      weightAr: ["٥٠٠ غرام", "١ كجم", "تعبئة بالجملة"],
      origin: "UAE",
      originAr: "الإمارات",
      storage: "-18°C",
      storageAr: "-١٨ درجة مئوية",
      packaging: ["Vacuum Sealed", "Frozen Packs"],
      packagingAr: ["مغلق ومفرغ من الهواء", "عبوات مجمدة"],
    },
    benefits: ["Ready-Sliced", "100% Halal Certified", "Tender & Delicious", "Easy to Cook"],
    benefitsAr: [
      "مقطعة وجاهزة للطهي مباشرة",
      "حلال معتمد ١٠٠٪",
      "قوام طري ونكهة لذيذة",
      "سهلة التحضير وسريعة",
    ],
  },
};

export const categoryMap = {
  "frozen-meat": {
    title: "Frozen Meat Products",
    titleAr: "منتجات اللحوم المجمدة",
    gradient: "from-red-900 via-red-800 to-red-950",
    products: ["beef-cubes", "lamb-chops", "beef-mince", "mutton-cuts"],
  },
  "frozen-chicken": {
    title: "Frozen Chicken Products",
    titleAr: "منتجات الدجاج المجمد",
    gradient: "from-amber-900 via-amber-800 to-amber-950",
    products: ["chicken-breast", "chicken-wings", "whole-chicken", "drumsticks"],
  },
  "frozen-seafood": {
    title: "Frozen Seafood Products",
    titleAr: "منتجات المأكولات البحرية المجمدة",
    gradient: "from-blue-900 via-blue-800 to-blue-950",
    products: ["fish-fillets", "shrimps", "salmon", "squid-rings"],
  },
};

export const categoryGradients = {
  "Frozen Meat": "from-red-900 to-red-950",
  "Frozen Chicken": "from-amber-900 to-amber-950",
  "Frozen Seafood": "from-blue-900 to-blue-950",
};
